name: RideApplication Pipeline

on:
  push:
    branches: [ "master", "rideDev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: "abhi@18"
          MYSQL_DATABASE: ride_db
        ports:
          - 3306:3306
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ride-backend-jar
          path: target/*.jar